#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 53f8a96e-9a14-4241-8cd4-06ea3bbb7380
# Source File: C:\Users\Kitsu\Documents\Powershell\Progetti Completi Originali\BarCode_Generator\GUI\GEN_Barcode.psf
#------------------------------------------------------------------------

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       09/11/2021 20:25
     Generated by:       Kitsu
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2020
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-GEN_Barcode_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formBarcodeGenerator = New-Object 'System.Windows.Forms.Form'
	$buttonNext = New-Object 'System.Windows.Forms.Button'
	$buttonPrev = New-Object 'System.Windows.Forms.Button'
	$buttonExit = New-Object 'System.Windows.Forms.Button'
	$tabcontrol1 = New-Object 'System.Windows.Forms.TabControl'
	$tabpage1 = New-Object 'System.Windows.Forms.TabPage'
	$textboxPathExcel = New-Object 'System.Windows.Forms.TextBox'
	$labelIlFileDiEsempioAlPer = New-Object 'System.Windows.Forms.Label'
	$buttonImportaDaExcel = New-Object 'System.Windows.Forms.Button'
	$buttonGeneraBarcode = New-Object 'System.Windows.Forms.Button'
	$labelEAN13Only = New-Object 'System.Windows.Forms.Label'
	$labelBarcodeGenerator = New-Object 'System.Windows.Forms.Label'
	$labelInserisciRigaPerRiga = New-Object 'System.Windows.Forms.Label'
	$TXTBOX_Excel = New-Object 'System.Windows.Forms.RichTextBox'
	$openfiledialog1 = New-Object 'System.Windows.Forms.OpenFileDialog'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formBarcodeGenerator_Load = {
		UpdateNavButtons
		
		if (Test-Path $PWD\Risultati)
		{
			return
		}
		else
		{
			mkdir $PWD\Risultati
		}
		
	}
	
	function Load-ExcelFileFromPath
	{
		
	}
	
	function Remove-Variables
	{
		
		Remove-Variable $row* -ErrorAction SilentlyContinue
		Remove-Variable $Rows* -ErrorAction SilentlyContinue
		
	}
	function Set-ExcelPath ($parameter1, $parameter2)
	{
		$openfiledialog1.ShowDialog()
		
		$FilePath = $openfiledialog1.FileName
		
		$textboxPathExcel.Text = $FilePath
		
		
	}
	#Convert-XlRangeToImage -Path $Path -workSheetname $workSheetname -range $range -destination "$pwd\temp.png" -show
	
	function UpdateNavButtons
	{
		$buttonNext.Enabled = $tabcontrol1.SelectedIndex -lt $tabcontrol1.TabCount - 1
		$buttonPrev.Enabled = $tabcontrol1.SelectedIndex -gt 0
	}
	
	$buttonPrev_Click = {
		if ($tabcontrol1.SelectedIndex -gt 0)
		{
			$tabcontrol1.SelectedIndex--
		}
		UpdateNavButtons
	}
	
	$buttonNext_Click = {
		if ($tabcontrol1.SelectedIndex -lt $tabcontrol1.TabCount - 1)
		{
			$tabcontrol1.SelectedIndex++
		}
		UpdateNavButtons
	}
	
	$buttonGeneraBarcode_Click = {
		
		if ($TXTBOX_Excel.Lines -eq 0)
		{
			[System.Windows.Forms.MessageBox]::Show('Sei sicuro di aver importato il file excel?', "ERRORE NESSUN BARCODE INSERITO") #cancel close if button is using DialogResult
			return
		}
		
		else
		{
			#Convert-XlRangeToImage -Path $Path -workSheetname $workSheetname -range $range -destination "$pwd\temp.png" -show
			
			$Path = "$pwd\Resource\EAN_13.xlsx"
			#Worksheet name - if none is specified "Sheet1" will be assumed
			
			$workSheetname = "Layout"
			#Range of cells within the sheet, e.g "A1:Z99"
			
			$range = "G1:J7"
			#A bmp, png or jpg file where the result will be saved
			
			$destination = "$pwd\Risultati\.png"
			#If specified opens the image in the default viewer.
			
			[switch]$show
			
			$extension = $destination -replace '^.*\.(\w+)$', '$1'
			
			if ($extension -in @('JPEG', 'BMP', 'PNG'))
			{
				$Format = [system.Drawing.Imaging.ImageFormat]$extension
			} #if we don't recognise the extension OR if it is JPG with an E, use JPEG format
			else { $Format = [system.Drawing.Imaging.ImageFormat]::Jpeg }
			Write-Progress -Activity "Exporting $range of $workSheetname in $Path" -Status "Starting Excel"
			$xlApp = New-Object -ComObject "Excel.Application"
			Write-Progress -Activity "Exporting $range of $workSheetname in $Path" -Status "Opening Workbook and copying data"
			$xlWbk = $xlApp.Workbooks.Open($Path)
			
			$xlApp.visible = $true
			
			$list = $TXTBOX_Excel.Lines | Where{ $_ } | ForEach{ $_.Trim() }
			
			$lines = $TXTBOX_Excel.Lines
			$TXTBOX_Excel.Lines = $list #Pulisce da Lines Vuote
			
			$Inputstring = $lines
			$CharArray = $InputString.Split(" ")
			
			$CharArray.Split('', [System.StringSplitOptions]::RemoveEmptyEntries)
			
			$CharArrayNumber = $CharArray | measure
			
			for ($i = 0; $i -lt $CharArrayNumber.Count; $i++)
			{
				$CharArray1Lenght = $CharArray[$i] | Measure-Object -Character
				
				[int]$test = $CharArray1Lenght.Characters
				
				[int]$13 = 13
				
				if ($CharArray1Lenght.Characters -notlike 13)
				{
					$lineaconerrore = $CharArray[$i]
					
					$TestoErrore = "Ogni seriale ha solo 13 caratteri`nL'errore è nella linea "
					
					[console]::beep(1000, 500)
					[System.Windows.Forms.MessageBox]::Show('Sei sicuro di aver importato il file excel?', "RILEVATO ERROE NEI BARCODE") #cancel close if button is using DialogResult
					
					return
					
				}
				for ($i = 1; $i -lt $CharArrayNumber.Count; $i++)
				{
					$xlWbk.Worksheets("Input Barcode").Select()
					$xlWbk.ActiveSheet.Cells(1, 32).Value2 = $CharArray[$i]
					
					Write-Progress -Activity "Exporting $range of $workSheetname in $Path" -Status "Opening Workbook and copying data"
					
					$xlWbk.Worksheets($workSheetname).Select()
					$xlWbk.ActiveSheet.Range($range).Select() | Out-Null
					$xlApp.Selection.Copy() | Out-Null
					
					# Get-Clipboard came in with PS5. Older versions can use [System.Windows.Clipboard] but it is ugly.
					
					$Destination_Number = ($destination.Length - 4)
					
					$image = Get-Clipboard -Format Image
					$image.Save($destination.Insert($Destination_Number, "$i"), $Format)
					
					Write-Progress -Activity "Exporting $range of $workSheetname in $Path" -Completed
					
					Write-Progress -Activity "Exporting $range of $workSheetname in $Path" -Status "Closing Excel"
					
					# $xlApp.Quit()
					
					Write-Progress -Activity "Exporting $range of $workSheetname in $Path" -Completed
					if ($show) { Start-Process -FilePath $destination }
					else { Get-Item -Path $destination.Insert($Destination_Number, "$i") }
					
				}
				$xlWbk.close($false)
				$xlApp.Quit()
				While ([System.Runtime.Interopservices.Marshal]::ReleaseComObject($xlApp) -ge 0) { }
				while ([System.Runtime.Interopservices.Marshal]::ReleaseComObject($xlWbk) -ge 0) { }
				Remove-Variable xlApp, xlWbk # Rimuovi le due variabili create
				
			}
		}
	}
	$buttonImportaDaExcel_Click = {
		
		Set-ExcelPath
		
		$xl = New-Object -ComObject Excel.Application
		$xl.Visible = $false
		$wb = $xl.Workbooks.Open($textboxPathExcel.Text)
		
		# Prendi la prima colonna
		$data = $wb.Worksheets[1].UsedRange.Rows.Columns[1].Value2
		$i = 0
		foreach ($row in $wb.Worksheets[1].UsedRange.Rows.Columns[1])
		{
			
			$TXTBOX_Excel.AppendText($wb.Worksheets[1].UsedRange.Rows.Columns[1].Value2)
			
			$i++
		}
		
		$Inputstring = $TXTBOX_Excel.Text
		$TXTBOX_Excel.Lines = $InputString.Split(" ")
		
		$list = $TXTBOX_Excel.Lines | Where{ $_ } | ForEach{ $_.Trim() }
		
		$TXTBOX_Excel.Lines = $list
		
		#$TXTBOX_Excel.Text = $data -split [Environment]::NewLine
		
		#$TXTBOX_Excel.Lines = $TXTBOX_Excel.Text -split [Environment]::NewLine
		
		#$TXTBOX_Excel.Lines.Split('', [System.StringSplitOptions]::RemoveEmptyEntries)
		
		#$TXTBOX_Excel.Text = $TXTBOX_Excel.Text| Where-Object { $_ } | Select -Unique
		
		# Chiudi excel aperto per prendere i dati
		$wb.close()
		$xl.Quit()
		While ([System.Runtime.Interopservices.Marshal]::ReleaseComObject($wb) -ge 0) { }
		while ([System.Runtime.Interopservices.Marshal]::ReleaseComObject($xl) -ge 0) { }
		Remove-Variable xl, wb # Rimuovi le due variabili create
		
		
	}
	
	$labelInserisciRigaPerRiga_Click = {
		#TODO: Place custom script here
		
	}
	
	$buttonApriXlxsEsempio_Click = {
		#TODO: Place custom script here
		
	}
	
	
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formBarcodeGenerator.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonNext.remove_Click($buttonNext_Click)
			$buttonPrev.remove_Click($buttonPrev_Click)
			$buttonImportaDaExcel.remove_Click($buttonImportaDaExcel_Click)
			$buttonGeneraBarcode.remove_Click($buttonGeneraBarcode_Click)
			$labelInserisciRigaPerRiga.remove_Click($labelInserisciRigaPerRiga_Click)
			$formBarcodeGenerator.remove_Load($formBarcodeGenerator_Load)
			$formBarcodeGenerator.remove_Load($Form_StateCorrection_Load)
			$formBarcodeGenerator.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formBarcodeGenerator.SuspendLayout()
	$tabcontrol1.SuspendLayout()
	$tabpage1.SuspendLayout()
	#
	# formBarcodeGenerator
	#
	$formBarcodeGenerator.Controls.Add($buttonNext)
	$formBarcodeGenerator.Controls.Add($buttonPrev)
	$formBarcodeGenerator.Controls.Add($buttonExit)
	$formBarcodeGenerator.Controls.Add($tabcontrol1)
	$formBarcodeGenerator.AutoScaleDimensions = '6, 13'
	$formBarcodeGenerator.AutoScaleMode = 'Font'
	$formBarcodeGenerator.AutoSize = $True
	$formBarcodeGenerator.BackColor = 'ActiveCaption'
	$formBarcodeGenerator.ClientSize = '514, 320'
	#region Binary Data
	$formBarcodeGenerator.Icon = [System.Convert]::FromBase64String('
AAABAAcAEBAAAAEAGABoAwAAdgAAAEBAAAABACAAKEIAAN4DAAAwMAAAAQAgAKglAAAGRgAAKCgA
AAEAIABoGgAArmsAACAgAAABACAAqBAAABaGAAAYGAAAAQAgAIgJAAC+lgAAFBQAAAEAIAC4BgAA
RqAAACgAAAAQAAAAIAAAAAEAGAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAABoaGhpaWlpaWlpaWlp
aWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWlpaWloaGhpaWn+/v7/////////////////////
//////////////////////////////9paWlpaWn+/v7/////////////////////////////////
//////////////////9paWlpaWn+/v7///9gYGBgYGBgYGBgYGD///////9gYGBgYGBgYGBgYGD/
//////9paWlpaWn+/v7///////////////////////////////////////////////////9paWlp
aWn+/v7///9gYGBgYGBgYGBgYGD///////9gYGBgYGBgYGBgYGD///////9paWlpaWn+/v7/////
//////////////////////////////////////////////9paWlpaWn+/v7///9gYGBgYGBgYGBg
YGD///////9gYGBgYGBgYGBgYGD///////9paWlpaWn+/v7/////////////////////////////
//////////////////////9paWlpaWn+/v7///9gYGBgYGBgYGBgYGD///////9gYGBgYGBgYGBg
YGD///////9paWlpaWn+/v7///////////////////////////////////////////////////9p
aWlpaWn9/f3///////////////////////////////////////////////////9paWmIrFWIrFWI
rFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWI
rFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWI
rFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWIrFWI
rFWIrFWIrFWIrFWIrFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAEAAAACAAAAAAQAgAAAAAAAAQgAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4QXh4eOF4eHj/eHh4
/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/
eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94
eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4
eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHjdeXl5PgAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAHh4eOZ4eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/
eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94
eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4
eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4
/3h4eP94eHj/eHh4/3h4eN0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/fHx8////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////f39/3h4eP94eHj+AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAeHh4/3x8fP//////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP98fHz/////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAB4eHj/fHx8////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4/3x8fP//////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAHh4eP98fHz/////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/fHx8////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAeHh4/3x8fP//////////////////////////////////////c3Nz/3Nzc/9zc3P/
c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////////////////////c3Nz/3Nzc/9z
c3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz//////////////////////9zc3P/c3Nz/3Nz
c/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz////////////////////////////////
//39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP96enr/////////////////
/////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9z
c3P//////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nz
c///////////////////////c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz
/3Nzc//////////////////////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAB4eHj/enp6////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4/3p6ev//////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAHh4eP96enr/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////9
/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/enp6////////////////////
//////////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz
//////////////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/
/////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9z
c3P//////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAeHh4/3p6ev//////////////////////////////////////c3Nz/3Nzc/9zc3P/c3Nz
/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////////////////////c3Nz/3Nzc/9zc3P/
c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz//////////////////////9zc3P/c3Nz/3Nzc/9z
c3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz//////////////////////////////////39
/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP96enr/////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAB4eHj/enp6////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////f39
/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4/3p6ev//////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAHh4eP96enr//////////////////////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9z
c3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P//////////////////////3Nzc/9zc3P/c3Nz/3Nz
c/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////////////////////c3Nz/3Nzc/9zc3P/c3Nz
/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc//////////////////////////////////9/f3/
eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/enp6////////////////////////
//////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz////
//////////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/////
/////////////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/
/////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAeHh4/3p6ev//////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////39/f94
eHj/eHh4+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP96enr/////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////9/f3/eHh4/3h4ePsAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAB4eHj/enp6////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////f39/3h4
eP94eHj7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4/3p6ev//////////////////////////
////////////c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////
////////////////c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz////////
//////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz////
//////////////////////////////39/f94eHj/eHh4+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AHh4eP96enr//////////////////////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/
c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P//////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9z
c3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////////////////////c3Nz/3Nzc/9zc3P/c3Nz/3Nz
c/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc//////////////////////////////////9/f3/eHh4
/3h4ePsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/enp6////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////f39/3h4eP94eHj7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
eHh4/3p6ev//////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////39/f94eHj/
eHh4+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP96enr/////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////9/f3/eHh4/3h4ePsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4
eHj/enp6//////////////////////////////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nz
c/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz//////////////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz
/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P//////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/
c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P//////////////////////////////////f39/3h4eP94
eHj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4/3p6ev//////////////////////////////
////////c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////////
////////////c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz////////////
//////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz////////
//////////////////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4
eP96enr/////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////9/f3/eHh4/3h4
eP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/enp6////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4
/3p6ev//////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////39/f94eHj/eHh4
/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP96enr/////////////////////////////////
/////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/////////////
/////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////////////
////////c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc///////////
///////////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/
enp6//////////////////////////////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nzc/9z
c3P/c3Nz/3Nzc/9zc3P/c3Nz//////////////////////9zc3P/c3Nz/3Nzc/9zc3P/c3Nz/3Nz
c/9zc3P/c3Nz/3Nzc/9zc3P//////////////////////3Nzc/9zc3P/c3Nz/3Nzc/9zc3P/c3Nz
/3Nzc/9zc3P/c3Nz/3Nzc/9zc3P//////////////////////////////////f39/3h4eP94eHj/
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4/3p6ev//////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////39/f94eHj/eHh4/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP96
enr/////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////9/f3/eHh4/3h4eP8A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/enp6////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4/3p6
ev//////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////39/f94eHj/eHh4/wAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eP96enr/////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////9/f3/eHh4/3h4eP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHj/enp6
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////f39/3h4eP94eHj/AAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAiKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIisVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAACIrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/wAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAIisVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAiKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIisVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf8AAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAACIrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAia5Ve4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iq5VjwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////////////////////////
////////////////4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAA
AAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAA
AAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAA
B+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH
4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfg
AAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AA
AAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAA
AAAAAAfgAAAAAAAAB+AAAAAAAAAH4AAAAAAAAAf/////////////////////////////////////
/////////////////////////////////////ygAAAAwAAAAYAAAAAEAIAAAAAAAgCUAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eNd4eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/
eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94
eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4
eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHjSAAAAAAAAAAAAAAAAAAAAAHx8fP94eHj/eHh4
/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/
eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94
eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/eHh4/3h4eP94eHj/AAAAAAAA
AAAAAAAAeHh4B3x8fP98fHz/////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4Dnx8fP98fHz/////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4Dnx8fP98
fHz/////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////f39/3h4eP94eHj/
AAAAAAAAAAAAAAAAeHh4Dnx8fP98fHz/////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4Dnx8fP98fHz/////////////////
/////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////////2BgYP9g
YGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////////2BgYP9gYGD/YGBg/2Bg
YP9gYGD/YGBg/2BgYP9gYGD//////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4
Dnx8fP98fHz/////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////f39/3h4
eP94eHj/AAAAAAAAAAAAAAAAeHh4Dnx8fP98fHz/////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4B3x8fP98fHz/////////
/////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////////////
/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////////2BgYP9gYGD/
YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////f39/3h4eP94eHj/AAAAAAAAAAAA
AAAAeHh4BHp6ev96enr/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/
/////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////
/////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////////2Bg
YP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////f39/3h4eP94eHj/AAAA
AAAAAAAAAAAAeHh4BHp6ev96enr/////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6
ev96enr//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////
/////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////////
/////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////f39/3h4eP94
eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAA
eHh4BHp6ev96enr//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9g
YGD//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////
/////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////f39
/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAA
AAAAAAAAeHh4BHp6ev96enr//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg
/2BgYP9gYGD//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/
/////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////
/////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96
enr/////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////f39/3h4eP94eHj/
AAAAAAAAAAAAAAAAeHh4BHp6ev96enr//////////////////////2BgYP9gYGD/YGBg/2BgYP9g
YGD/YGBg/2BgYP9gYGD//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2Bg
YP9gYGD//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////
/////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4
BHp6ev96enr/////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////f39/3h4
eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr//////////////////////2BgYP9gYGD/YGBg
/2BgYP9gYGD/YGBg/2BgYP9gYGD//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/
YGBg/2BgYP9gYGD//////////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9g
YGD//////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeHh4BHp6ev96enr/////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAA
AAAAeHh4CHp6ev96enr/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/f39/3h4eP94eHj/AAAAAAAAAAAAAAAAeXl5DHp6ev96enr/////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////f39/3h4eP94eHj/AAAAAAAAAAAAAAAAgX15DHp6ev96enr/
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////f39/3h4eP94eHj/AAAA
AAAAAAAAAAAAlH5mEYisVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAn31bDYisVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAq3hEBYis
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/AAAAAAAAAAAAAAAAAAAAAIisVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAAAAAAIisVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAA
AAAAAIisVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/AAAAAAAAAAAAAAAAAAAAAIisVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAAAAAAIisVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////8A
AP///////wAA////////AADAAAAAAAMAAMAAAAAAAwAAgAAAAAADAACAAAAAAAMAAIAAAAAAAwAA
gAAAAAADAACAAAAAAAMAAIAAAAAAAwAAgAAAAAADAACAAAAAAAMAAIAAAAAAAwAAgAAAAAADAACA
AAAAAAMAAIAAAAAAAwAAgAAAAAADAACAAAAAAAMAAIAAAAAAAwAAgAAAAAADAACAAAAAAAMAAIAA
AAAAAwAAgAAAAAADAACAAAAAAAMAAIAAAAAAAwAAgAAAAAADAACAAAAAAAMAAIAAAAAAAwAAgAAA
AAADAACAAAAAAAMAAIAAAAAAAwAAgAAAAAADAACAAAAAAAMAAIAAAAAAAwAAgAAAAAADAACAAAAA
AAMAAIAAAAAAAwAAwAAAAAADAADAAAAAAAMAAMAAAAAAAwAAwAAAAAADAADAAAAAAAMAAP//////
/wAA////////AAD///////8AAP///////wAA////////AAAoAAAAKAAAAFAAAAABACAAAAAAAEAa
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoaGj/aGho
/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/
aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9o
aGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/AAAAAAAAAAB4eHgDaGho////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////+/v7/aGho/wAAAAAAAAAAeHh4BmhoaP//////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////v7+
/2hoaP8AAAAAAAAAAHh4eAloaGj/////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////7+/v9oaGj/AAAAAAAA
AAB4eHgJaGho//////////////////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////
////////////YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/////////////////2BgYP9gYGD/
YGBg/2BgYP9gYGD/YGBg/2BgYP/////////////////+/v7/aGho/wAAAAAAAAAAeHh4CWhoaP//
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////v7+/2hoaP8AAAAAAAAAAHh4eAhoaGj/////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////7+/v9oaGj/AAAAAAAAAAB4eHgHaGho//////////////////////9gYGD/YGBg
/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////////YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/
YGBg/////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP/////////////////+
/v7/aGho/wAAAAAAAAAAeHh4BmhoaP//////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////v7+/2hoaP8AAAAA
AAAAAHh4eARoaGj/////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////7+/v9oaGj/AAAAAAAAAAB4eHgCaGho
//////////////////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////////
YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/////////////////2BgYP9gYGD/YGBg/2BgYP9g
YGD/YGBg/2BgYP/////////////////+/v7/aGho/wAAAAAAAAAAeHh4AmhoaP//////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////v7+/2hoaP8AAAAAAAAAAHh4eAJoaGj/////////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//7+/v9oaGj/AAAAAAAAAAB4eHgCaGho//////////////////////9gYGD/YGBg/2BgYP9gYGD/
YGBg/2BgYP9gYGD/////////////////YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg////////
/////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP/////////////////+/v7/aGho/wAA
AAAAAAAAeHh4AmhoaP//////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////v7+/2hoaP8AAAAAAAAAAHh4eAJo
aGj/////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////7+/v9oaGj/AAAAAAAAAAB4eHgCaGho////////////
//////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////////YGBg/2BgYP9g
YGD/YGBg/2BgYP9gYGD/YGBg/////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2Bg
YP/////////////////+/v7/aGho/wAAAAAAAAAAeHh4AmhoaP//////////////////////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////v7+/2hoaP8AAAAAAAAAAHh4eAJoaGj/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////7+/v9oaGj/
AAAAAAAAAAB4eHgCaGho//////////////////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9g
YGD/////////////////YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/////////////////2Bg
YP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP/////////////////+/v7/aGho/wAAAAAAAAAAeHh4
AmhoaP//////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////v7+/2hoaP8AAAAAAAAAAHh4eAJoaGj/////////
////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////7+/v9oaGj/AAAAAAAAAAB4eHgEaGho//////////////////////9g
YGD/YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD/////////////////YGBg/2BgYP9gYGD/YGBg/2Bg
YP9gYGD/YGBg/////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP//////////
///////+/v7/aGho/wAAAAAAAAAAeXl5BmhoaP//////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////v7+/2ho
aP8AAAAAAAAAAH17eQZoaGj/////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////7+/v9oaGj/AAAAAAAAAACC
fnoGaGho////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////+/v7/aGho/wAAAAAAAAAAkn9rCoisVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf8AAAAAAAAAAJl9YASIrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAiKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/wAAAAAAAAAAAAAAAIisVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf8AAAAAAAAA
AAAAAACIrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAAAAAAAAiKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/wAAAAAAAAAAAAAAAIisVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////AAAA//////8AAAD//////wAA
AMAAAAABAAAAgAAAAAEAAACAAAAAAQAAAIAAAAABAAAAgAAAAAEAAACAAAAAAQAAAIAAAAABAAAA
gAAAAAEAAACAAAAAAQAAAIAAAAABAAAAgAAAAAEAAACAAAAAAQAAAIAAAAABAAAAgAAAAAEAAACA
AAAAAQAAAIAAAAABAAAAgAAAAAEAAACAAAAAAQAAAIAAAAABAAAAgAAAAAEAAACAAAAAAQAAAIAA
AAABAAAAgAAAAAEAAACAAAAAAQAAAIAAAAABAAAAgAAAAAEAAACAAAAAAQAAAIAAAAABAAAAwAAA
AAEAAADAAAAAAQAAAMAAAAABAAAAwAAAAAEAAADAAAAAAQAAAP//////AAAA//////8AAAD/////
/wAAAP//////AAAAKAAAACAAAABAAAAAAQAgAAAAAACAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2ho
aP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho
/2hoaP9oaGj/aGho/2hoaP9oaGj/aGho/2hoaP9oaGj/AAAAAHh4eANoaGj/////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////v7+/2hoaP8AAAAAeHh4Bmho
aP//////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////+/v7/
aGho/wAAAAB4eHgJaGho////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////7+/v9oaGj/AAAAAHh4eAloaGj/////////////////YGBg/2BgYP9gYGD/YGBg
/2BgYP9gYGD///////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP///////////2BgYP9gYGD/
YGBg/2BgYP9gYGD/YGBg/////////////v7+/2hoaP8AAAAAeHh4CGhoaP//////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////+/v7/aGho/wAAAAB4eHgHaGho
/////////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/
YGBg/2BgYP9gYGD///////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP////////////7+/v9o
aGj/AAAAAHh4eAZoaGj/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////v7+/2hoaP8AAAAAeHh4BmhoaP////////////////9gYGD/YGBg/2BgYP9gYGD/
YGBg/2BgYP///////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9g
YGD/YGBg/2BgYP9gYGD////////////+/v7/aGho/wAAAAB4eHgGaGho////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////7+/v9oaGj/AAAAAHh4eAZoaGj/
////////////////YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD///////////9gYGD/YGBg/2BgYP9g
YGD/YGBg/2BgYP///////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg/////////////v7+/2ho
aP8AAAAAeHh4BmhoaP//////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////+/v7/aGho/wAAAAB4eHgEaGho/////////////////2BgYP9gYGD/YGBg/2BgYP9g
YGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD///////////9gYGD/YGBg/2Bg
YP9gYGD/YGBg/2BgYP////////////7+/v9oaGj/AAAAAHh4eAJoaGj/////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////v7+/2hoaP8AAAAAeHh4AmhoaP//
//////////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP///////////2BgYP9gYGD/YGBg/2Bg
YP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg/2BgYP9gYGD////////////+/v7/aGho
/wAAAAB4eHgCaGho////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////7+/v9oaGj/AAAAAHh4eARoaGj/////////////////YGBg/2BgYP9gYGD/YGBg/2Bg
YP9gYGD///////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP///////////2BgYP9gYGD/YGBg
/2BgYP9gYGD/YGBg/////////////v7+/2hoaP8AAAAAeHh4BGhoaP//////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////+/v7/aGho/wAAAAB4eHgEaGho////
/////////////2BgYP9gYGD/YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg
/2BgYP9gYGD///////////9gYGD/YGBg/2BgYP9gYGD/YGBg/2BgYP////////////7+/v9oaGj/
AAAAAHl5eQRoaGj/////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////v7+/2hoaP8AAAAAgH16BGhoaP//////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
///////////////////////////+/v7/aGho/wAAAACIf3UIaGho////////////////////////
////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////7+/v9oaGj/AAAAAKB8WBSIrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf8A
AAAAqnhFAoisVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/wAAAAAAAAAAiKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/AAAAAAAAAACIrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf8AAAAAAAAAAIisVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/wAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////4AAAAEA
AAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAA
AAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAYAAAAGAAAABgAAAAf//////////////
/ygAAAAYAAAAMAAAAAEAIAAAAAAAYAkAAAAAAAAAAAAAAAAAAAAAAABoaGj/Z2dn/2dnZ/9nZ2f/
Z2dn/2dnZ/9nZ2f/Z2dn/2dnZ/9nZ2f/Z2dn/2dnZ/9nZ2f/Z2dn/2dnZ/9nZ2f/Z2dn/2dnZ/9n
Z2f/Z2dn/2dnZ/9nZ2f/Z2dn/2hoaP9nZ2f/////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/2dnZ/9nZ2f/////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////2dnZ/9nZ2f/////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////2dnZ/9nZ2f///////////9gYGD/YGBg/2BgYP9gYGD/YGBg
////////////YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg/2BgYP//////
/////2dnZ/9nZ2f/////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////2dnZ/9nZ2f/////////
//9gYGD/YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg////////////YGBg
/2BgYP9gYGD/YGBg/2BgYP///////////2dnZ/9nZ2f/////////////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////2dnZ/9nZ2f///////////9gYGD/YGBg/2BgYP9gYGD/YGBg////////////YGBg/2Bg
YP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg/2BgYP///////////2dnZ/9oaGj/////
////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////2dnZ/9oaGj///////////9gYGD/YGBg/2BgYP9g
YGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg/2Bg
YP///////////2dnZ/9oaGj/////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////2dnZ/9oaGj/
//////////9gYGD/YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg////////
////YGBg/2BgYP9gYGD/YGBg/2BgYP///////////2dnZ/9oaGj/////////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////2dnZ/9oaGj///////////9gYGD/YGBg/2BgYP9gYGD/YGBg////////////
YGBg/2BgYP9gYGD/YGBg////////////YGBg/2BgYP9gYGD/YGBg/2BgYP///////////2dnZ/9o
aGj/////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////2dnZ/9oaGj/////////////////////
////////////////////////////////////////////////////////////////////////////
/////////////////////2dnZ/9oaGj/////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////2dn
Z/+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wAoAAAAFAAAACgA
AAABACAAAAAAAJAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoaGj/
aWlp/2lpaf9paWn/aWlp/2lpaf9paWn/aWlp/2lpaf9paWn/aWlp/2lpaf9paWn/aWlp/2lpaf9p
aWn/aWlp/2lpaf9paWn/aGho/2lpaf/+/v7/////////////////////////////////////////
//////////////////////////////////////////////////9paWn/aWlp//7+/v//////////
////////////////////////////////////////////////////////////////////////////
/////2lpaf9paWn//v7+//////9gYGD/YGBg/2BgYP9gYGD//////2BgYP9gYGD/YGBg/2BgYP//
////YGBg/2BgYP9gYGD/YGBg////////////aWlp/2lpaf/+/v7/////////////////////////
//////////////////////////////////////////////////////////////////9paWn/aWlp
//7+/v//////YGBg/2BgYP9gYGD/YGBg//////9gYGD/YGBg/2BgYP9gYGD//////2BgYP9gYGD/
YGBg/2BgYP///////////2lpaf9paWn//v7+////////////////////////////////////////
////////////////////////////////////////////////////aWlp/2lpaf/+/v7//////2Bg
YP9gYGD/YGBg/2BgYP//////YGBg/2BgYP9gYGD/YGBg//////9gYGD/YGBg/2BgYP9gYGD/////
//////9paWn/aWlp//7+/v//////////////////////////////////////////////////////
/////////////////////////////////////2lpaf9paWn//v7+//////9gYGD/YGBg/2BgYP9g
YGD//////2BgYP9gYGD/YGBg/2BgYP//////YGBg/2BgYP9gYGD/YGBg////////////aWlp/2lp
af/+/v7/////////////////////////////////////////////////////////////////////
//////////////////////9paWn/aWlp//7+/v//////YGBg/2BgYP9gYGD/YGBg//////9gYGD/
YGBg/2BgYP9gYGD//////2BgYP9gYGD/YGBg/2BgYP///////////2lpaf9paWn//f39////////
////////////////////////////////////////////////////////////////////////////
////////aWlp/2lpaf/9/f3/////////////////////////////////////////////////////
//////////////////////////////////////9paWn/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4is
Vf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV
/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/
iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+IrFX/iKxV/4isVf+I
rFX/iKxV/4isVf8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//8AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///AA')
	#endregion
	$formBarcodeGenerator.MaximumSize = '530, 359'
	$formBarcodeGenerator.MinimumSize = '530, 359'
	$formBarcodeGenerator.Name = 'formBarcodeGenerator'
	$formBarcodeGenerator.StartPosition = 'CenterParent'
	$formBarcodeGenerator.Text = 'Barcode Generator'
	$formBarcodeGenerator.add_Load($formBarcodeGenerator_Load)
	#
	# buttonNext
	#
	$buttonNext.Anchor = 'Bottom, Left'
	$buttonNext.Font = 'Webdings, 8.25pt'
	$buttonNext.Location = '58, 285'
	$buttonNext.Name = 'buttonNext'
	$buttonNext.Size = '35, 23'
	$buttonNext.TabIndex = 3
	$buttonNext.Text = '8'
	$buttonNext.TextAlign = 'TopCenter'
	$buttonNext.UseCompatibleTextRendering = $True
	$buttonNext.UseVisualStyleBackColor = $True
	$buttonNext.add_Click($buttonNext_Click)
	#
	# buttonPrev
	#
	$buttonPrev.Anchor = 'Bottom, Left'
	$buttonPrev.Font = 'Webdings, 8.25pt'
	$buttonPrev.Location = '17, 285'
	$buttonPrev.Name = 'buttonPrev'
	$buttonPrev.Size = '35, 23'
	$buttonPrev.TabIndex = 2
	$buttonPrev.Text = '7'
	$buttonPrev.TextAlign = 'TopCenter'
	$buttonPrev.UseCompatibleTextRendering = $True
	$buttonPrev.UseVisualStyleBackColor = $True
	$buttonPrev.add_Click($buttonPrev_Click)
	#
	# buttonExit
	#
	$buttonExit.Anchor = 'Bottom, Right'
	$buttonExit.DialogResult = 'OK'
	$buttonExit.Location = '422, 285'
	$buttonExit.Name = 'buttonExit'
	$buttonExit.Size = '75, 23'
	$buttonExit.TabIndex = 1
	$buttonExit.Text = 'Exit'
	$buttonExit.UseCompatibleTextRendering = $True
	$buttonExit.UseVisualStyleBackColor = $True
	#
	# tabcontrol1
	#
	$tabcontrol1.Controls.Add($tabpage1)
	$tabcontrol1.Anchor = 'Top, Bottom, Left, Right'
	$tabcontrol1.Location = '13, 12'
	$tabcontrol1.Name = 'tabcontrol1'
	$tabcontrol1.SelectedIndex = 0
	$tabcontrol1.Size = '489, 267'
	$tabcontrol1.TabIndex = 0
	#
	# tabpage1
	#
	$tabpage1.Controls.Add($textboxPathExcel)
	$tabpage1.Controls.Add($labelIlFileDiEsempioAlPer)
	$tabpage1.Controls.Add($buttonImportaDaExcel)
	$tabpage1.Controls.Add($buttonGeneraBarcode)
	$tabpage1.Controls.Add($labelEAN13Only)
	$tabpage1.Controls.Add($labelBarcodeGenerator)
	$tabpage1.Controls.Add($labelInserisciRigaPerRiga)
	$tabpage1.Controls.Add($TXTBOX_Excel)
	$tabpage1.BackColor = 'DarkOrange'
	$tabpage1.Location = '4, 22'
	$tabpage1.Name = 'tabpage1'
	$tabpage1.Padding = '3, 3, 3, 3'
	$tabpage1.Size = '481, 241'
	$tabpage1.TabIndex = 0
	$tabpage1.Text = 'Home'
	#
	# textboxPathExcel
	#
	$textboxPathExcel.Location = '137, 156'
	$textboxPathExcel.Name = 'textboxPathExcel'
	$textboxPathExcel.Size = '235, 20'
	$textboxPathExcel.TabIndex = 8
	#
	# labelIlFileDiEsempioAlPer
	#
	$labelIlFileDiEsempioAlPer.AutoSize = $True
	$labelIlFileDiEsempioAlPer.Location = '229, 143'
	$labelIlFileDiEsempioAlPer.Name = 'labelIlFileDiEsempioAlPer'
	$labelIlFileDiEsempioAlPer.Size = '0, 16'
	$labelIlFileDiEsempioAlPer.TabIndex = 7
	$labelIlFileDiEsempioAlPer.TextAlign = 'MiddleCenter'
	$labelIlFileDiEsempioAlPer.UseCompatibleTextRendering = $True
	#
	# buttonImportaDaExcel
	#
	$buttonImportaDaExcel.Location = '261, 182'
	$buttonImportaDaExcel.Name = 'buttonImportaDaExcel'
	$buttonImportaDaExcel.Size = '111, 23'
	$buttonImportaDaExcel.TabIndex = 5
	$buttonImportaDaExcel.Text = 'Importa da Excel'
	$buttonImportaDaExcel.UseCompatibleTextRendering = $True
	$buttonImportaDaExcel.UseVisualStyleBackColor = $True
	$buttonImportaDaExcel.add_Click($buttonImportaDaExcel_Click)
	#
	# buttonGeneraBarcode
	#
	$buttonGeneraBarcode.Location = '198, 211'
	$buttonGeneraBarcode.Name = 'buttonGeneraBarcode'
	$buttonGeneraBarcode.Size = '101, 23'
	$buttonGeneraBarcode.TabIndex = 4
	$buttonGeneraBarcode.Text = 'Genera Barcode!'
	$buttonGeneraBarcode.UseCompatibleTextRendering = $True
	$buttonGeneraBarcode.UseVisualStyleBackColor = $True
	$buttonGeneraBarcode.add_Click($buttonGeneraBarcode_Click)
	#
	# labelEAN13Only
	#
	$labelEAN13Only.AutoSize = $True
	$labelEAN13Only.BackColor = 'Transparent'
	$labelEAN13Only.Font = 'Microsoft Sans Serif, 6pt'
	$labelEAN13Only.Location = '228, 28'
	$labelEAN13Only.Name = 'labelEAN13Only'
	$labelEAN13Only.Size = '53, 14'
	$labelEAN13Only.TabIndex = 3
	$labelEAN13Only.Text = '*EAN-13 only'
	$labelEAN13Only.UseCompatibleTextRendering = $True
	#
	# labelBarcodeGenerator
	#
	$labelBarcodeGenerator.AutoSize = $True
	$labelBarcodeGenerator.BackColor = 'Transparent'
	$labelBarcodeGenerator.Font = 'Stencil, 16pt'
	$labelBarcodeGenerator.ForeColor = 'Yellow'
	$labelBarcodeGenerator.Location = '136, 7'
	$labelBarcodeGenerator.Name = 'labelBarcodeGenerator'
	$labelBarcodeGenerator.Size = '236, 31'
	$labelBarcodeGenerator.TabIndex = 2
	$labelBarcodeGenerator.Text = 'Barcode Generator'
	$labelBarcodeGenerator.UseCompatibleTextRendering = $True
	#
	# labelInserisciRigaPerRiga
	#
	$labelInserisciRigaPerRiga.AutoSize = $True
	$labelInserisciRigaPerRiga.Location = '136, 42'
	$labelInserisciRigaPerRiga.Name = 'labelInserisciRigaPerRiga'
	$labelInserisciRigaPerRiga.Size = '251, 42'
	$labelInserisciRigaPerRiga.TabIndex = 1
	$labelInserisciRigaPerRiga.Text = 'Inserisci riga per riga i barcode, 
oppure premi importa da excel.
(Premi su file di esempio per aprire un esempio)
'
	$labelInserisciRigaPerRiga.TextAlign = 'MiddleCenter'
	$labelInserisciRigaPerRiga.UseCompatibleTextRendering = $True
	$labelInserisciRigaPerRiga.add_Click($labelInserisciRigaPerRiga_Click)
	#
	# TXTBOX_Excel
	#
	$TXTBOX_Excel.Location = '7, 7'
	$TXTBOX_Excel.MaxLength = 99999999
	$TXTBOX_Excel.Name = 'TXTBOX_Excel'
	$TXTBOX_Excel.Size = '123, 228'
	$TXTBOX_Excel.TabIndex = 0
	$TXTBOX_Excel.Text = '

'
	#
	# openfiledialog1
	#
	$openfiledialog1.Filter = 'Foglio di lavoro di excel (*.xlsx)|*.xlsx|Tutti i file (*.*)|*.*'
	$openfiledialog1.InitialDirectory = "$pwd"
	$tabpage1.ResumeLayout()
	$tabcontrol1.ResumeLayout()
	$formBarcodeGenerator.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formBarcodeGenerator.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formBarcodeGenerator.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formBarcodeGenerator.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formBarcodeGenerator.ShowDialog()

} #End Function

#Call the form
Show-GEN_Barcode_psf | Out-Null
